### ISSUE TITLE
Alfred configuration question

### ISSUE THREAD

**Issue by mkschulze** [BenjaminOddou/alfred-emoji-wine#5]
Hello, I'm trying to setup your workflow, but it seems that whenever I type something in alfred it automatically wants to search for it in google. :)
I probably misconfigured something, maybe you could point me to it, that would be really nice. I have Python 3.11.4 installed and also Pillow. thx!

![image](https://github.com/BenjaminOddou/alfred-emoji-wine/assets/3390820/f93c4c75-90e4-431a-8121-2647bba8e65f)

![image](https://github.com/BenjaminOddou/alfred-emoji-wine/assets/3390820/e53cec38-4f6d-48a7-b066-2c19d14fd936)

![image](https://github.com/BenjaminOddou/alfred-emoji-wine/assets/3390820/70f298d3-d11c-4cce-85e3-7c73b4d64bb8)

**Comment by BenjaminOddou** [comment]
Hello @mkschulze, could you check the log file `emoji_wine.log` here : `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine` ?

**Comment by holyalex** [comment]
Hi Ben, I'm having the same issue with both the plex workflow and this one.  The debugger gives me this 

`11:51:59.647] Emoji Wine[Script Filter] Queuing argument '(null)'
[11:51:59.709] Emoji Wine[Script Filter] Script with argv '(null)' finished
[11:51:59.710] ERROR: Emoji Wine[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C16189CF-5A51-4949-9571-15C060D1B4D4/wine.py", line 3, in <module>
    from utils import config, api_file_path, tags_file_path, icons_folder_path, language
  File "/Users/alex/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.C16189CF-5A51-4949-9571-15C060D1B4D4/utils.py", line 32, in <module>
    log_file_handler = log.FileHandler(os.path.join(cache_folder_path, f'emoji_wine.log'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alex/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine/emoji_wine.log'`

**Comment by BenjaminOddou** [comment]
@holyalex Many thanks for the feedback. I thought logging library was native on python but I probably installed it. I'll release a fix very soon for both this workflow and the plex workflow.

**Comment by BenjaminOddou** [comment]
@holyalex @mkschulze it should be fixed with the latest release (same for Alfred Plex workflow). Don't hesitate to come back to me in case you see another bug.

**Comment by holyalex** [comment]
looking forward to it!
